# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from random import randrange
from PyQt5 import QtCore, QtGui, QtWidgets

# Data Base
arr_admin=[{"username":"lahijan11","password":"1111"},{"username":"astara10","password":"1010"},{"username":"langaroud12","password":"1212"},{"username":"rasht23","password":"2323"},{"username":"kalachay13","password":"1313"},]
arr_bus=[{"id":"0","type":"Volvo","origin":"لاهیجان","destination":"آذربایجان شرقی","capacity":"35","remaining":"33","admin":"lahijan11"},{"id":"1","type":"Volvo VIP","origin":"لاهیجان","destination":"اصفهان","capacity":"50","remaining":"49","admin":"lahijan11"},{"id":"2","type":"Man","origin":"لنگرود","destination":"آذربایجان شرقی","capacity":"35","remaining":"35","admin":"langaroud12"},{"id":"3","type":"Man","origin":"لنگرود","destination":"اصفهان","capacity":"50","remaining":"50","admin":"langaroud12"}]
select_bus={}
arr_passanger=[{"id":"0","name":"آرتا فلاح پور","sex":"مرد","idbus":"0"},{"id":"0","name":"آرتا فلاح پور","sex":"مرد","idbus":"0"},{"id":"0","name":"آرتا فلاح پور","sex":"مرد","idbus":"1"}]
admin=""
arr_listbuy=[]
arr_busADMIN=[]
arr_passanger_forbus=[]
arr_listbus=[]
def sortlistbus(o,d):
    global arr_listbus
    arr_listbus = []
    for i in arr_bus :
        if(i["origin"]==o and i["destination"]==d):
            arr_listbus.append(i)

def busadminf(adminname):
    global arr_busADMIN,arr_bus
    arr_busADMIN=[arr_bus[i] for i in range(len(arr_bus)) if arr_bus[i]["admin"]==adminname]
def buspassangerf(select_bus):
    global arr_passanger,arr_passanger_forbus
    arr_passanger_forbus=[arr_passanger[i] for i in range(len(arr_passanger)) if arr_passanger[i]["idbus"]==select_bus["id"]]
def busbuyblit(destination,origin):
    global arr_listbuy,arr_bus
    arr_listbuy=[arr_bus[i] for i in range(len(arr_bus)) if arr_bus[i]["destination"]==destination and arr_bus[i]["origin"]==origin]

mabda,maghsad="",""
#global viwe 
Adminpage = ""
ui3 = ""
Passenger = ""
ui4 = ""
hallo_arta = ""
ui5 = ""
form = ""
ui6= ""



class Ui_Form(object):
    def setupUi(self, Form):
        global select_bus
        Form.setObjectName("Form")
        Form.resize(635, 508)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_13 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setText(select_bus["destination"]+"                            ")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setText(select_bus["origin"]+"                         ")
        self.label_10.setObjectName("label_10")
        
        
        self.horizontalLayout_2.addWidget(self.label_10)
        self.label_7 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_10.setFont(font)
        self.label_8.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setText("                  "+select_bus["capacity"])
        self.label_3.setObjectName("label_3")
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setText("                  "+select_bus["remaining"])
        self.label_4.setObjectName("label_4")
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("height:50px")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("مرد")
        self.comboBox.addItem("زن")
        self.horizontalLayout.addWidget(self.comboBox)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("height:50px\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("height:50px\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        
        
        
        self.pushButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("height:50px\n"
"")
        self.pushButton.clicked.connect(self.ticket)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def ticket(self) :
        global select_bus,form,select_bus
        text=self.lineEdit.text()
        name=self.lineEdit_2.text()
        sex = self.comboBox.currentText()
        if(self.validationinput(text,int(select_bus["remaining"]))  and name !="" and name !=" "  and name !="  ") :
            obj = {"id":str(randrange(1000000)),"name":name,"sex":sex,"idbus":select_bus["id"]}
            for i in range(int(text)):
                arr_passanger.append(obj)
            for i in arr_bus:
                if i["id"] == select_bus["id"]:
                    i["remaining"] = str(int(i["remaining"])-int(text))
            form.hide()
            Main.show()

        
    def validationinput(self,txt,num):
        text = [i for i in txt] 
        flag2 =True
        if len(text)==1:
                if text[0]=="0":
                        flag2=False
        if len(text)>1:
                if text[0]=="0":
                        flag2=False
        flag = True
        numerr=0
        for i in text:
                flag=True
                for j in list(range(0,10)) :
                        if str(j) == i:
                              flag = False
                if flag:
                      numerr += 1 
        if(len(text)>0 and flag2 ):
                if(num>=int(txt)):
                    return True
                else:
                    return False
        else:
                return False

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_13.setText(_translate("Form", "به ترمینال مسافر بری خوش آمدید"))
        self.label_9.setText(_translate("Form", "مقصد :"))
        self.label_7.setText(_translate("Form", "مبدا :"))
        self.label_5.setText(_translate("Form", "مقدار ظرفیت کل اتوبوس :"))
        self.label_6.setText(_translate("Form", "تعداد بلیط باقی مانده :"))
        self.label.setText(_translate("Form", "تعداد بلیط :"))
        self.label_2.setText(_translate("Form", "نام شخص رزرو کننده بلیط :"))
        self.pushButton.setText(_translate("Form", "رزور بلیط"))



class Ui_hallo_arta(object):
    def setupUi(self, hallo_arta):
        global mabda , maghsad ,arr_listbus
        hallo_arta.setObjectName("hallo_arta")
        hallo_arta.resize(669, 696)
        self.centralwidget = QtWidgets.QWidget(hallo_arta)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(hallo_arta)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(hallo_arta)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(hallo_arta)
        self.label_6.setText(maghsad)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_4 = QtWidgets.QLabel(hallo_arta)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(hallo_arta)
        self.label_5.setText(mabda)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(hallo_arta)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_5.setFont(font)
        self.label_6.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(hallo_arta)
        self.tableWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setAcceptDrops(False)
        self.tableWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(len(arr_listbus))
        for i in range(len(arr_listbus)) :
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setVerticalHeaderItem(i, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        for i in range(len(arr_listbus)) :
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 1, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 2, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 3, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 4, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton2 = QtWidgets.QPushButton(hallo_arta)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton2.setFont(font)
        self.pushButton2.setText("برگشت به خانه")
        self.pushButton2.setStyleSheet("height:30px")
        self.pushButton2.setObjectName("pushButton")
        self.pushButton2.clicked.connect(self.backhome)
        self.horizontalLayout.addWidget(self.pushButton2)
        self.pushButton = QtWidgets.QPushButton(hallo_arta)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("height:30px")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.selectbusrezerve)
        self.horizontalLayout.addWidget(self.pushButton)
        
        self.lineEdit = QtWidgets.QLineEdit(hallo_arta)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label = QtWidgets.QLabel(hallo_arta)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.retranslateUi(hallo_arta)
        QtCore.QMetaObject.connectSlotsByName(hallo_arta)
    def selectbusrezerve(self):
        global arr_listbus , select_bus,form,ui6,hallo_arta
        text = self.lineEdit.text()
        if self.validationinput(text,len(arr_listbus)) :
            select_bus = arr_listbus[int(text)-1]
            form = QtWidgets.QWidget()
            ui6 = Ui_Form()
            ui6.setupUi(form)
            form.show()
            hallo_arta.hide()

    def backhome(self):
        Main.show()
        hallo_arta.hide()
    def validationinput(self,txt,num):
        text = [i for i in txt] 
        flag2 =True
        if len(text)==1:
                if text[0]=="0":
                        flag2=False
        if len(text)>1:
                if text[0]=="0":
                        flag2=False
        flag = True
        numerr=0
        for i in text:
                flag=True
                for j in list(range(0,10)) :
                        if str(j) == i:
                              flag = False
                if flag:
                      numerr += 1 
        if(len(text)>0 and flag2 ):
                if(num>=int(txt)):
                    return True
                else:
                    return False
        else:
                return False

    def retranslateUi(self, hallo_arta):
        global arr_listbus
        _translate = QtCore.QCoreApplication.translate
        hallo_arta.setWindowTitle(_translate("hallo_arta", "لیست مسافران"))
        self.label_2.setText(_translate("hallo_arta", "خوش آمدید به ترمینال مسافر بری "))
        self.label_4.setText(_translate("hallo_arta", "مقصد : "))
        self.label_3.setText(_translate("hallo_arta", "مبدا : "))
        self.tableWidget.setSortingEnabled(False)
        for i in range(len(arr_listbus)) :
            item = self.tableWidget.verticalHeaderItem(i)
            item.setText(_translate("hallo_arta", str(i+1)))
        for i in range(len(arr_listbus)) :
            item = self.tableWidget.item(i, 0)
            item.setText(_translate("hallo_arta", arr_listbus[i]["type"]))
            item = self.tableWidget.item(i, 1)
            item.setText(_translate("hallo_arta", arr_listbus[i]["capacity"]))
            item = self.tableWidget.item(i, 2)
            item.setText(_translate("hallo_arta", arr_listbus[i]["remaining"]))
            item = self.tableWidget.item(i, 3)
            item.setText(_translate("hallo_arta", arr_listbus[i]["origin"]))
            item = self.tableWidget.item(i, 4)
            item.setText(_translate("hallo_arta", arr_listbus[i]["destination"]))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("hallo_arta", "نوع ماشین"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("hallo_arta", "ظرفیت"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("hallo_arta", "ظرفیت باقی مانده"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("hallo_arta", "مبدا"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("hallo_arta", "مقصد"))
        self.pushButton.setText(_translate("hallo_arta", "رزرو بلیط"))
        self.label.setText(_translate("hallo_arta", "شماره اتوبوس : "))


class passenger(object):
    def setupUi(self, log_in_page3):
        global select_bus,arr_passanger_forbus
        log_in_page3.setObjectName("log_in_page3")
        log_in_page3.resize(864, 713)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("bus.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        log_in_page3.setWindowIcon(icon)
        log_in_page3.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(log_in_page3)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("height:40px")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.addpassanger)
        self.horizontalLayout.addWidget(self.pushButton)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("height:40px")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("height:40px")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.destination = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.destination.setFont(font)
        self.destination.setText(select_bus["destination"]+"                      ")
        self.destination.setObjectName("destination")
        self.horizontalLayout_2.addWidget(self.destination)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.origin = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.origin.setFont(font)
        self.origin.setText(select_bus["origin"]+"                      ")
        self.origin.setObjectName("origin")
        self.horizontalLayout_2.addWidget(self.origin)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.typemacin = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.typemacin.setFont(font)
        self.typemacin.setText("                      "+select_bus["type"])
        self.typemacin.setObjectName("typemacin")
        self.horizontalLayout_2.addWidget(self.typemacin)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setText("                                      "+select_bus["capacity"])
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.monde = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.monde.setFont(font)
        self.monde.setText("                                                "+select_bus["remaining"])
        self.monde.setObjectName("monde")
        self.horizontalLayout_4.addWidget(self.monde)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setTabKeyNavigation(True)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(len(arr_passanger_forbus))
        self.tableWidget.setEnabled(True)
        for i in range(len(arr_passanger_forbus)) :
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setVerticalHeaderItem(i, item)
        for i in range(len(arr_passanger_forbus)) :
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("height:30px")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.deletepassanger)
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("height:30px")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        log_in_page3.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(log_in_page3)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 864, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        log_in_page3.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(log_in_page3)
        self.statusbar.setObjectName("statusbar")
        log_in_page3.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(log_in_page3)
        self.action.setObjectName("action")
        self.action.triggered.connect(self.backhome)
        self.action_3 = QtWidgets.QAction(log_in_page3)
        self.action_3.setObjectName("action_3")
        self.action_3.triggered.connect(self.backadminpage)
        self.menu.addAction(self.action)
        self.menu.addSeparator()
        self.menu.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())
        self.retranslateUi(log_in_page3)
        QtCore.QMetaObject.connectSlotsByName(log_in_page3)
    def backhome(self):
        global Passenger
        Main.show()
        Passenger.hide()
    def backadminpage(self):
        global Adminpage,ui3
        Adminpage = QtWidgets.QMainWindow()
        ui3 = adminpage()
        ui3.setupUi(Adminpage)
        Adminpage.show()
        Passenger.hide()
    def deletepassanger(self):
        global select_bus,arr_passanger,arr_passanger_forbus,arr_bus,arr_bus,arr_busADMIN
        Id = self.lineEdit.text()
        if self.validationinput(Id,len(arr_passanger_forbus)):
            self.tableWidget.removeRow(int(Id)-1)
            machin_id = arr_passanger_forbus[int(Id)-1]["id"]
            for i in range(len(arr_passanger)):
                if(machin_id == arr_passanger[i]["id"]):
                    arr_passanger.pop(i)
                    break
            arr_passanger_forbus.pop(int(Id)-1)
            self.tableWidget.setRowCount(len(arr_passanger_forbus))
            for i in arr_bus:
                if i["id"] == select_bus["id"]:
                    i["remaining"] = str(int(i["remaining"])+1)
            self.monde.setText("                                                "+select_bus["remaining"])
    def addpassanger(self):
        global select_bus,arr_passanger,arr_passanger_forbus,arr_bus,arr_busADMIN
        if int(select_bus["remaining"]) > 0 :
            sex=self.comboBox.currentText()
            name=self.lineEdit_2.text()
            if(name != "" and name != " " and name != "  " and name != "   " ):
                obj = {"id":str(randrange(1000000)),"name":name,"sex":sex,"idbus":select_bus["id"]}
                arr_passanger.append(obj)
                arr_passanger_forbus.append(obj)
                self.tableWidget.setRowCount(len(arr_passanger_forbus))
                self.tableWidget.setItem(len(arr_passanger_forbus)-1,0,QtWidgets.QTableWidgetItem(name))
                self.tableWidget.setItem(len(arr_passanger_forbus)-1,1,QtWidgets.QTableWidgetItem(sex))
                for i in arr_bus:
                    if i["id"] == select_bus["id"]:
                        i["remaining"] = str(int(i["remaining"])-1)
                self.monde.setText("                                                "+select_bus["remaining"])
    def validationinput(self,txt,num):
        text = [i for i in txt] 
        flag2 =True
        if len(text)==1:
                if text[0]=="0":
                        flag2=False
        if len(text)>1:
                if text[0]=="0":
                        flag2=False
        flag = True
        numerr=0
        for i in text:
                flag=True
                for j in list(range(0,10)) :
                        if str(j) == i:
                              flag = False
                if flag:
                      numerr += 1 
        if(len(text)>0 and flag2 ):
                if(num>=int(txt)):
                    return True
                else:
                    return False
        else:
                return False

    def retranslateUi(self, log_in_page3):
        _translate = QtCore.QCoreApplication.translate
        log_in_page3.setWindowTitle(_translate("log_in_page3", "Admin"))
        self.pushButton.setText(_translate("log_in_page3", "  افزودن مسافر  "))
        self.comboBox.setItemText(0, _translate("log_in_page3", "زن"))
        self.comboBox.setItemText(1, _translate("log_in_page3", "مرد"))
        self.label_2.setText(_translate("log_in_page3", "جنسیت :"))
        self.label.setText(_translate("log_in_page3", "نام و نام خانوادگی :"))
        self.label_12.setText(_translate("log_in_page3", " "))
        self.label_5.setText(_translate("log_in_page3", "مقصد:"))
        self.label_4.setText(_translate("log_in_page3", "مبدا:"))
        self.label_3.setText(_translate("log_in_page3", "نوع ماشین : "))
        self.label_13.setText(_translate("log_in_page3", " "))
        self.label_7.setText(_translate("log_in_page3", "ظرفیت کل:"))
        self.label_6.setText(_translate("log_in_page3", "ظرفیت باقی مانده:"))
        self.tableWidget.setSortingEnabled(False)
        for i in range(len(arr_passanger_forbus)) :
            item = self.tableWidget.verticalHeaderItem(i)
            item.setText(_translate("log_in_page2", str(i+1)))
        for i in range(len(arr_passanger_forbus)) :
            item = self.tableWidget.item(i, 0)
            item.setText(_translate("log_in_page2", arr_passanger_forbus[i]["name"]))
            item = self.tableWidget.item(i, 1)
            item.setText(_translate("log_in_page2", arr_passanger_forbus[i]["sex"]))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("log_in_page3", "نام و نام خانوادگی"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("log_in_page3", "جنسیت"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("log_in_page3", "حذف مسافر"))
        self.label_9.setText(_translate("log_in_page3", "شماره صندلی مسافر :"))
        self.menu.setTitle(_translate("log_in_page3", "ابزار ها"))
        self.action.setText(_translate("log_in_page3", "برگشت به خانه"))
        self.action_3.setText(_translate("log_in_page3", "برگشت به پنل ادمین"))



class adminpage(object):
    def setupUi(self, log_in_page2):
        self.log_in_page2 = log_in_page2
        log_in_page2.setObjectName("log_in_page2")
        log_in_page2.resize(779, 758)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("bus.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        log_in_page2.setWindowIcon(icon)
        global arr_busADMIN
        self.centralwidget = QtWidgets.QWidget(log_in_page2)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_capacity = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_capacity.setEnabled(True)
        self.lineEdit_capacity.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"height:40px")
        self.lineEdit_capacity.setObjectName("lineEdit_capacity")
        self.horizontalLayout.addWidget(self.lineEdit_capacity)
        self.label_capacity = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_capacity.setFont(font)
        self.label_capacity.setObjectName("label_capacity")
        self.horizontalLayout.addWidget(self.label_capacity)
        self.comboBox_machane = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_machane.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"height:50px")
        self.comboBox_machane.setObjectName("comboBox_machane")
        self.comboBox_machane.addItem("")
        self.comboBox_machane.addItem("")
        self.comboBox_machane.addItem("")
        self.comboBox_machane.addItem("")
        self.comboBox_machane.addItem("")
        self.comboBox_machane.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_machane)
        self.label_machine = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_machine.setFont(font)
        self.label_machine.setObjectName("label_machine")
        self.horizontalLayout.addWidget(self.label_machine)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_confirm = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_confirm.setFont(font)
        self.pushButton_confirm.setStyleSheet("height:40px")
        self.pushButton_confirm.clicked.connect(self.add_bus)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.horizontalLayout_2.addWidget(self.pushButton_confirm)
        self.comboBox_destonatin = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_destonatin.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"height:40px")
        self.comboBox_destonatin.setObjectName("comboBox_destonatin")
        for i in range(31):
            self.comboBox_destonatin.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_destonatin)
        self.label_destonation = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_destonation.setFont(font)
        self.label_destonation.setObjectName("label_destonation")
        self.horizontalLayout_2.addWidget(self.label_destonation)
        self.comboBox_origin = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_origin.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"height:40px")
        self.comboBox_origin.setObjectName("comboBox_origin")
        for i in range(5):
            self.comboBox_origin.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_origin)
        self.label_origin = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_origin.setFont(font)
        self.label_origin.setObjectName("label_origin")
        self.horizontalLayout_2.addWidget(self.label_origin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setMinimumSize(QtCore.QSize(761, 498))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(len(arr_busADMIN))
        self.tableWidget.setEnabled(True)
        for i in range(len(arr_busADMIN)) :
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setVerticalHeaderItem(i, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.Dense2Pattern)
        item.setForeground(brush)
        for i in range(len(arr_busADMIN)) :
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 1, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 2, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 3, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 4, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(148)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.tableWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton2.setFont(font)
        self.pushButton2.setStyleSheet("height:30px")
        self.pushButton2.setObjectName("pushButton")
        self.pushButton2.setText("حذف")
        self.pushButton2.clicked.connect(self.delete)
        self.horizontalLayout_3.addWidget(self.pushButton2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("height:30px")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.showpassanger)
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("height:30px")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        log_in_page2.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(log_in_page2)
        self.statusbar.setObjectName("statusbar")
        log_in_page2.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(log_in_page2)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 779, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        log_in_page2.setMenuBar(self.menuBar)
        self.action = QtWidgets.QAction(log_in_page2)
        self.action.setObjectName("action")
        self.action.triggered.connect(self.backhome)
        self.menu.addAction(self.action)
        self.menuBar.addAction(self.menu.menuAction())
        self.retranslateUi(log_in_page2)
        QtCore.QMetaObject.connectSlotsByName(log_in_page2)
    
    def showpassanger(self):
        global Adminpage,Passenger,ui4,arr_busADMIN,select_bus,buspassangerf
        Id = self.lineEdit.text()
        if(self.validationinput(Id,len(arr_busADMIN))):
            select_bus = arr_busADMIN[int(Id)-1]
            buspassangerf(select_bus)
            Passenger = QtWidgets.QMainWindow()
            ui4 = passenger()
            ui4.setupUi(Passenger) 
            Passenger.show()
            Adminpage.hide()

    def backhome(self):
        global Adminpage
        Main.show()
        Adminpage.hide()

    def delete(self):
        global arr_bus ,arr_busADMIN
        Id = self.lineEdit.text()
        if self.validationinput(Id,len(arr_busADMIN)):
            self.tableWidget.removeRow(int(Id)-1)
            machin_id = arr_busADMIN[int(Id)-1]["id"]
            for i in range(len(arr_bus)):
                if(machin_id == arr_bus[i]["id"]):
                    arr_bus.pop(i)
                    break
            arr_busADMIN.pop(int(Id)-1)
            self.tableWidget.setRowCount(len(arr_busADMIN))
    def validationinput(self,txt,num):
        text = [i for i in txt] 
        flag2 =True
        if len(text)==1:
                if text[0]=="0":
                        flag2=False
        if len(text)>1:
                if text[0]=="0":
                        flag2=False
        flag = True
        numerr=0
        for i in text:
                flag=True
                for j in list(range(0,10)) :
                        if str(j) == i:
                              flag = False
                if flag:
                      numerr += 1 
        if(len(text)>0 and flag2 ):
                if(num>=int(txt)):
                    return True
                else:
                    return False
        else:
                return False


    def add_bus(self):
        if(self.validationinput(self.lineEdit_capacity.text(),101)):
            typem=self.comboBox_machane.currentText()
            origin=self.comboBox_origin.currentText()
            destonatin=self.comboBox_destonatin.currentText()
            capacity=self.lineEdit_capacity.text()
            global admin,arr_bus,arr_busADMIN
            obj = {"id":str(randrange(1000000)),"type":typem,"origin":origin,"destination":destonatin,"capacity":capacity,"remaining":capacity,"admin":admin}
            arr_bus.append(obj)
            arr_busADMIN.append(obj)
            self.tableWidget.setRowCount(len(arr_busADMIN))
            self.tableWidget.setItem(len(arr_busADMIN)-1,0,QtWidgets.QTableWidgetItem(typem))
            self.tableWidget.setItem(len(arr_busADMIN)-1,1,QtWidgets.QTableWidgetItem(capacity))
            self.tableWidget.setItem(len(arr_busADMIN)-1,2,QtWidgets.QTableWidgetItem(capacity))
            self.tableWidget.setItem(len(arr_busADMIN)-1,3,QtWidgets.QTableWidgetItem(origin))
            self.tableWidget.setItem(len(arr_busADMIN)-1,4,QtWidgets.QTableWidgetItem(destonatin))
            
    def retranslateUi(self, log_in_page2):
        _translate = QtCore.QCoreApplication.translate
        global arr_busADMIN
        log_in_page2.setWindowTitle(_translate("log_in_page2", "پنل ادمین"))
        self.label_capacity.setText(_translate("log_in_page2", "ظرفیت :"))
        self.comboBox_machane.setItemText(0, _translate("log_in_page2", "Volvo"))
        self.comboBox_machane.setItemText(1, _translate("log_in_page2", "Volvo VIP"))
        self.comboBox_machane.setItemText(2, _translate("log_in_page2", "Man"))
        self.comboBox_machane.setItemText(3, _translate("log_in_page2", "Man VIP"))
        self.comboBox_machane.setItemText(4, _translate("log_in_page2", "Scania"))
        self.comboBox_machane.setItemText(5, _translate("log_in_page2", "Scania VIP"))
        self.label_machine.setText(_translate("log_in_page2", "ماشین :"))
        self.pushButton_confirm.setText(_translate("log_in_page2", "ثبت"))
        self.comboBox_destonatin.setItemText(0, _translate("log_in_page2", "آذربایجان شرقی"))
        self.comboBox_destonatin.setItemText(1, _translate("log_in_page2", "آذربایجان غربی"))
        self.comboBox_destonatin.setItemText(2, _translate("log_in_page2", "اردبیل"))
        self.comboBox_destonatin.setItemText(3, _translate("log_in_page2", "اردبیل"))
        self.comboBox_destonatin.setItemText(4, _translate("log_in_page2", "اصفهان"))
        self.comboBox_destonatin.setItemText(5, _translate("log_in_page2", "البرز"))
        self.comboBox_destonatin.setItemText(6, _translate("log_in_page2", "ایلام"))
        self.comboBox_destonatin.setItemText(7, _translate("log_in_page2", "بوشهر"))
        self.comboBox_destonatin.setItemText(8, _translate("log_in_page2", "تهران"))
        self.comboBox_destonatin.setItemText(9, _translate("log_in_page2", "چهارمحال و بختیاری"))
        self.comboBox_destonatin.setItemText(10, _translate("log_in_page2", "خراسان جنوبی"))
        self.comboBox_destonatin.setItemText(11, _translate("log_in_page2", "خراسان رضوی"))
        self.comboBox_destonatin.setItemText(12, _translate("log_in_page2", "خراسان شمالی"))
        self.comboBox_destonatin.setItemText(13, _translate("log_in_page2", "خوزستان"))
        self.comboBox_destonatin.setItemText(14, _translate("log_in_page2", "زنجان"))
        self.comboBox_destonatin.setItemText(15, _translate("log_in_page2", "سمنان"))
        self.comboBox_destonatin.setItemText(16, _translate("log_in_page2", "سیستان و بلوچستان"))
        self.comboBox_destonatin.setItemText(17, _translate("log_in_page2", "فارس"))
        self.comboBox_destonatin.setItemText(18, _translate("log_in_page2", "قزوین"))
        self.comboBox_destonatin.setItemText(19, _translate("log_in_page2", "قم"))
        self.comboBox_destonatin.setItemText(20, _translate("log_in_page2", "کردستان"))
        self.comboBox_destonatin.setItemText(21, _translate("log_in_page2", "کرمان"))
        self.comboBox_destonatin.setItemText(22, _translate("log_in_page2", "کرمانشاه"))
        self.comboBox_destonatin.setItemText(23, _translate("log_in_page2", "کهگیلویه و بویراحمد"))
        self.comboBox_destonatin.setItemText(24, _translate("log_in_page2", "گلستان"))
        self.comboBox_destonatin.setItemText(25, _translate("log_in_page2", "لرستان"))
        self.comboBox_destonatin.setItemText(26, _translate("log_in_page2", "مازندران"))
        self.comboBox_destonatin.setItemText(27, _translate("log_in_page2", "مرکزی"))
        self.comboBox_destonatin.setItemText(28, _translate("log_in_page2", "هرمزگان"))
        self.comboBox_destonatin.setItemText(29, _translate("log_in_page2", "همدان"))
        self.comboBox_destonatin.setItemText(30, _translate("log_in_page2", "یزد"))
        self.label_destonation.setText(_translate("log_in_page2", "مقصد :"))
        self.comboBox_origin.setItemText(0, _translate("log_in_page2", "لاهیجان"))
        self.comboBox_origin.setItemText(1, _translate("log_in_page2", "آستارا"))
        self.comboBox_origin.setItemText(2, _translate("log_in_page2", "لنگرود"))
        self.comboBox_origin.setItemText(3, _translate("log_in_page2", "کلاچای"))
        self.comboBox_origin.setItemText(4, _translate("log_in_page2", "رشت"))
        self.label_origin.setText(_translate("log_in_page2", "مبدا :"))
        
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("log_in_page2", "نوع ماشین"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("log_in_page2", "ظرفیت"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("log_in_page2", "ظرفیت باقی مانده"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("log_in_page2", "مبدا"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("log_in_page2", "مقصد"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        for i in range(len(arr_busADMIN)) :
            item = self.tableWidget.verticalHeaderItem(i)
            item.setText(_translate("log_in_page2", str(i+1)))
        for i in range(len(arr_busADMIN)) :
            item = self.tableWidget.item(i, 0)
            item.setText(_translate("log_in_page2", arr_busADMIN[i]["type"]))
            item = self.tableWidget.item(i, 1)
            item.setText(_translate("log_in_page2", arr_busADMIN[i]["capacity"]))
            item = self.tableWidget.item(i, 2)
            item.setText(_translate("log_in_page2", arr_busADMIN[i]["remaining"]))
            item = self.tableWidget.item(i, 3)
            item.setText(_translate("log_in_page2", arr_busADMIN[i]["origin"]))
            item = self.tableWidget.item(i, 4)
            item.setText(_translate("log_in_page2", arr_busADMIN[i]["destination"]))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("log_in_page2", "لیست مسافران"))
        self.label.setText(_translate("log_in_page2", "شماره ردیف اتوبوس :"))
        self.menu.setTitle(_translate("log_in_page2", "ابزار ها"))
        self.action.setText(_translate("log_in_page2", "برگشت به خانه"))

#! LOGIN CLASS

class login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(932, 647)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setStyleSheet("height:50px\n"
"")
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setStyleSheet("height:50")
        self.lineEdit_2.setObjectName("lineEdit_2")
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("height:60px")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.loginFunc)
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 779, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action.triggered.connect(self.backhome)
        self.menu.addAction(self.action)
        self.menuBar.addAction(self.menu.menuAction())
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def backhome(self):
        Main.show()
        Login.hide()
    def loginFunc(self):
        username=self.lineEdit.text()
        password=self.lineEdit_2.text()
        global arr_admin,admin,busadminf
        for i in arr_admin:
            if i['username'] == username and i['password'] == password :
                admin = username
                busadminf(username)
                Login.hide()
                global Adminpage,ui3
                Adminpage = QtWidgets.QMainWindow()
                ui3 = adminpage()
                ui3.setupUi(Adminpage)
                Adminpage.show()
                break
            else:
                print("not valid")
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "ورود به پنل ادمین"))
        self.label_10.setText(_translate("MainWindow", "                    "))
        self.label_13.setText(_translate("MainWindow", "                      "))
        self.label.setText(_translate("MainWindow", "نام کاربری  »"))
        self.label_11.setText(_translate("MainWindow", "                    "))
        self.label_12.setText(_translate("MainWindow", "                     "))
        self.label_9.setText(_translate("MainWindow", "         "))
        self.label_2.setText(_translate("MainWindow", "رمز ورود »"))
        self.label_8.setText(_translate("MainWindow", " "))
        self.pushButton.setText(_translate("MainWindow", "ورود"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.menu.setTitle(_translate("log_in_page2", "ابزار ها"))
        self.action.setText(_translate("log_in_page2", "برگشت به خانه"))
#! MAIN CLASS

class main(object):
    def setupUi(self, picture):
        picture.setObjectName("picture")
        picture.resize(750, 668)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("bus.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        picture.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(picture)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_mabda = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_mabda.setFont(font)
        self.label_mabda.setStyleSheet("")
        self.label_mabda.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mabda.setObjectName("label_mabda")
        self.horizontalLayout.addWidget(self.label_mabda)
        self.lable_maghsad = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        self.lable_maghsad.setFont(font)
        self.lable_maghsad.setStyleSheet("height:40px;")
        self.lable_maghsad.setAlignment(QtCore.Qt.AlignCenter)
        self.lable_maghsad.setObjectName("lable_maghsad")
        self.horizontalLayout.addWidget(self.lable_maghsad)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mabda_combo = QtWidgets.QComboBox(self.centralwidget)
        self.mabda_combo.setStyleSheet("height:50px;")
        self.mabda_combo.setObjectName("mabda_combo")
        font = QtGui.QFont()
        font.setPointSize(16)
        self.mabda_combo.setFont(font)
        self.mabda_combo.addItem("")
        self.mabda_combo.addItem("")
        self.mabda_combo.addItem("")
        self.mabda_combo.addItem("")
        self.mabda_combo.addItem("")
        self.mabda_combo.setItemText(5, "")
        self.horizontalLayout_2.addWidget(self.mabda_combo)
        self.maghsad_combo = QtWidgets.QComboBox(self.centralwidget)
        self.maghsad_combo.setStyleSheet("height:50px;")
        self.maghsad_combo.setObjectName("maghsad_combo")
        font = QtGui.QFont()
        font.setPointSize(16)
        self.maghsad_combo.setFont(font)
        for i in range(31):
            self.maghsad_combo.addItem("")
        self.horizontalLayout_2.addWidget(self.maghsad_combo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.picture_page1 = QtWidgets.QLabel(self.centralwidget)
        self.picture_page1.setStyleSheet("height:180px")
        self.picture_page1.setText("")
        self.picture_page1.setPixmap(QtGui.QPixmap("./img/otoboos.jpg"))
        self.picture_page1.setObjectName("picture_page1")
        self.picture_page1.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout_2.addWidget(self.picture_page1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.search_button.setFont(font)
        self.search_button.setStyleSheet("height:50px")
        self.search_button.setObjectName("search_button")
        self.search_button.clicked.connect(self.searchbus)
        self.verticalLayout_2.addWidget(self.search_button)
        picture.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(picture)
        self.statusbar.setObjectName("statusbar")
        picture.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(picture)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 750, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuadmin_login_page = QtWidgets.QMenu(self.menuBar)
        self.menuadmin_login_page.setObjectName("menuadmin_login_page")
        picture.setMenuBar(self.menuBar)
        self.actioncopy = QtWidgets.QAction(picture)
        self.actioncopy.setObjectName("actioncopy")
        self.actionpaste = QtWidgets.QAction(picture)
        self.actionpaste.setObjectName("actionpaste")
        self.actionExit = QtWidgets.QAction(picture)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("exit.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon1)
        self.actionExit.setObjectName("actionExit")
        self.actionmaximize = QtWidgets.QAction(picture)
        self.actionmaximize.setObjectName("actionmaximize")
        self.actionnormal_view = QtWidgets.QAction(picture)
        self.actionnormal_view.setObjectName("actionnormal_view")
        self.actionlogin_admin_page = QtWidgets.QAction(picture)
        self.actionlogin_admin_page.triggered.connect(self.changepage)
        self.actionlogin_admin_page.setObjectName("actionlogin_admin_page")
        self.menuadmin_login_page.addAction(self.actionlogin_admin_page)
        self.menuBar.addAction(self.menuadmin_login_page.menuAction())

        self.retranslateUi(picture)
        self.actionExit.triggered.connect(picture.close) # type: ignore
        self.actionmaximize.triggered.connect(picture.showMaximized) # type: ignore
        self.actionnormal_view.triggered.connect(picture.showNormal) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(picture)
    def searchbus(self):
        global hallo_arta , ui5 ,mabda,maghsad
        mabda = self.mabda_combo.currentText()
        maghsad = self.maghsad_combo.currentText()
        sortlistbus(mabda,maghsad)
        hallo_arta = QtWidgets.QWidget()
        ui5 = Ui_hallo_arta()
        ui5.setupUi(hallo_arta)
        hallo_arta.show()
        Main.hide()
        
    def changepage(self):
        Main.hide()
        Login.show()

    def retranslateUi(self, picture):
        _translate = QtCore.QCoreApplication.translate
        picture.setWindowTitle(_translate("picture", "رزرو بلیط اتوبوس"))
        self.label_mabda.setText(_translate("picture", "مبدا"))
        self.lable_maghsad.setText(_translate("picture", "مقصد"))
        self.mabda_combo.setItemText(0, _translate("picture", "لاهیجان"))
        self.mabda_combo.setItemText(1, _translate("picture", "لنگرود"))
        self.mabda_combo.setItemText(2, _translate("picture", "کلاچای"))
        self.mabda_combo.setItemText(3, _translate("picture", "رشت"))
        self.mabda_combo.setItemText(4, _translate("picture", "آستارا"))
        self.maghsad_combo.setItemText(0, _translate("picture", "آذربایجان شرقی"))
        self.maghsad_combo.setItemText(1, _translate("picture", "آذربایجان غربی"))
        self.maghsad_combo.setItemText(2, _translate("picture", "اردبیل"))
        self.maghsad_combo.setItemText(3, _translate("picture", "اصفهان"))
        self.maghsad_combo.setItemText(4, _translate("picture", "البرز"))
        self.maghsad_combo.setItemText(5, _translate("picture", "ایلام"))
        self.maghsad_combo.setItemText(6, _translate("picture", "بوشهر"))
        self.maghsad_combo.setItemText(7, _translate("picture", "تهران"))
        self.maghsad_combo.setItemText(8, _translate("picture", "چهارمحال بختیاری"))
        self.maghsad_combo.setItemText(9, _translate("picture", "خراسان جنوبی"))
        self.maghsad_combo.setItemText(10, _translate("picture", "خراسان شمالی"))
        self.maghsad_combo.setItemText(11, _translate("picture", "خراسان رضوی"))
        self.maghsad_combo.setItemText(12, _translate("picture", "خوزستان"))
        self.maghsad_combo.setItemText(13, _translate("picture", "زنجان"))
        self.maghsad_combo.setItemText(14, _translate("picture", "سمنان"))
        self.maghsad_combo.setItemText(15, _translate("picture", "سیستان و بلوچستان"))
        self.maghsad_combo.setItemText(16, _translate("picture", "فارس"))
        self.maghsad_combo.setItemText(17, _translate("picture", "قزوین"))
        self.maghsad_combo.setItemText(18, _translate("picture", "قم"))
        self.maghsad_combo.setItemText(19, _translate("picture", "کردستان"))
        self.maghsad_combo.setItemText(20, _translate("picture", "کرمان"))
        self.maghsad_combo.setItemText(21, _translate("picture", "کرمانشاه"))
        self.maghsad_combo.setItemText(22, _translate("picture", "کهکلویه و بویراحمد"))
        self.maghsad_combo.setItemText(23, _translate("picture", "گلستان"))
        self.maghsad_combo.setItemText(24, _translate("picture", "لرستان"))
        self.maghsad_combo.setItemText(25, _translate("picture", "مازندران"))
        self.maghsad_combo.setItemText(26, _translate("picture", "مرکزی"))
        self.maghsad_combo.setItemText(27, _translate("picture", "هرمزگان"))
        self.maghsad_combo.setItemText(28, _translate("picture", "همدان"))
        self.maghsad_combo.setItemText(29, _translate("picture", "یزد"))
        self.search_button.setText(_translate("picture", "جست وجو"))
        self.menuadmin_login_page.setTitle(_translate("picture", "ابزار ها"))
        self.actioncopy.setText(_translate("picture", "copy"))
        self.actioncopy.setWhatsThis(_translate("picture", "Copy"))
        self.actioncopy.setShortcut(_translate("picture", "Ctrl+C"))
        self.actionpaste.setText(_translate("picture", "paste"))
        self.actionpaste.setWhatsThis(_translate("picture", "paste"))
        self.actionpaste.setShortcut(_translate("picture", "Ctrl+V"))
        self.actionExit.setText(_translate("picture", "Exit"))
        self.actionExit.setStatusTip(_translate("picture", "click to exit"))
        self.actionmaximize.setText(_translate("picture", "maximize"))
        self.actionmaximize.setShortcut(_translate("picture", "Ctrl+M"))
        self.actionnormal_view.setText(_translate("picture", "normal"))
        self.actionnormal_view.setShortcut(_translate("picture", "Ctrl+N"))
        self.actionlogin_admin_page.setText(_translate("picture", "ورود به پنل ادمین"))
 


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = main()
    ui.setupUi(Main)
    Login = QtWidgets.QMainWindow()
    ui2 = login()
    ui2.setupUi(Login)
    Main.show()
    Login.hide()
    sys.exit(app.exec_())
